# Generated by Django 4.2.6 on 2023-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='desc',
            field=models.CharField(default='No description given', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.CharField(default='No owner specified', max_length=255, null=True),
        ),
    ]
